export { HomePage } from './home'
export { LoginPage } from './login'
export { RegisterPage } from './register'
export { ForgotPasswordPage } from './forgot-password'
export { ResetPasswordPage } from './reset-password'
export { ProtectedPage } from './protected'
