name: Автодеплой

on:
  push:
    branches:
      - main
      - sprint-6/step-1

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Подключение репозитория
        uses: actions/checkout@v2

      - name: Авторизация в реестре докер-контейнеров
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YA_TOKEN_REGISTRY }}

      - name: Сборка и отправка образа
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: cr.yandex/${{ vars.ID_REGISTRY }}/burger:prod

  deploy:
    needs: build-and-push
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Подключение репозитория
        uses: actions/checkout@v2

      - name: Вывести имя пользователя
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: whoami

      - name: Копирование docker-compose.yml на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose.yml
          target: /home/admin

      - name:  Получение образов и их запуск
        uses: appleboy/ssh-action@v1.0.3
        env:
          API_URI: ${{ vars.API_URI }}
          WS_URI: ${{ vars.WS_URI }}
          TAG: prod
          ID_REGISTRY: ${{ vars.ID_REGISTRY }}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: API_URI,WS_URI,TAG,ID_REGISTRY
          script: |
            docker login --username oauth --password ${{ secrets.YA_TOKEN_REGISTRY }} cr.yandex
            docker compose -f /home/admin/docker-compose.yml pull
            docker image prune -f
            docker compose -f /home/admin/docker-compose.yml -p ${{ github.event.repository.name }} up -d
